os: Visual Studio 2017

install:
  - git submodule update --init --recursive

assembly_info:
  patch: false

configuration:
  - Release

build_script:
  - ps: .\build.ps1 -Target "Appveyor" -Configuration "Release"

test: off
skip_tags: true