// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ShaderTools.VisualStudio
{
    static class Vsix
    {
        public const string Id = "ShaderTools.VisualStudio.d021429f-deae-410e-b18e-7b37a306bf5b";
        public const string Name = "Shader Tools for Visual Studio";
        public const string Description = @"Enhanced support for editing HLSL and Unity ShaderLab shaders in Visual Studio";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tim Jones";
        public const string Tags = "HLSL, Unity, ShaderLab, shader";
    }
}
